#!/bin/bash
echo "ALX"

clear
[A[A[A[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[Broot@ce2b1ccd3e06:/alx-zero_day/0x03-git/bash# clear

[A[B
root@ce2b1ccd3e06:/alx-zero_day/0x03-git/bash#clear

root@ce2b1ccd3e06:/alx-zero_day/0x03-git/bash# cat >  school
